scala:
  - 2.11.12
  - 2.12.11
  - 2.13.1

language: scala

script: >
  sbt ++$TRAVIS_SCALA_VERSION test check

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
