addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.33")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "3.9.19")
addSbtPlugin("com.github.gseitz"  % "sbt-release"              % "1.0.13")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                  % "2.0.1")
